apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-sample-pod
  labels:
    app: kubernetes-sample-pod
spec:
  containers:
    - name: kubernetes-sample-pod
      image: arisu1000/simple-container-app:latest
      ports:
        - containerPort: 8080
